### ISSUE TITLE
README: add 'Office customizations will be undone' after 'office: Implements the Microsoft Office Related STIGs'?

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [simeononsecurity/Windows-Optimize-Harden-Debloat#100]
**Is your feature request related to a problem? Please describe.**
I ran the script and - among other problems (how to get my screensaver back? How to customise the lock-screen?) - I noticed that many (all?) of my Microsoft Office customizations had been undone.

**Describe the solution you'd like**
At the least (and at most? I don't know) insert the warning suggested by my title.

**Describe alternatives you've considered**
I tried to reimplement my changes, and I was able to, save for the restoring of a Word 'addOn' - I couldn't get that to work any more.

**Additional context**
I reinstalled my old system (my whole C:) from a backup.

**Comment by LinuxOnTheDesktop** [comment]
Windows 10 Pro 22H2 (19045.4651).

**Comment by simeononsecurity** [comment]
> **Is your feature request related to a problem? Please describe.** I ran the script and - among other problems (how to get my screensaver back? How to customise the lock-screen?) - I noticed that many (all?) of my Microsoft Office customizations had been undone.
> 
> **Describe the solution you'd like** At the least (and at most? I don't know) insert the warning suggested by my title.
> 
> **Describe alternatives you've considered** I tried to reimplement my changes, and I was able to, save for the restoring of a Word 'addOn' - I couldn't get that to work any more.
> 
> **Additional context** I reinstalled my old system (my whole C:) from a backup.

You didn't answer the questions needed to help troubleshoot this effectively. Please see the bot message above.

I can say that this script doesn't modify your lockscreen or wallpaper. If that is happening to you, it is because of some other configuration on your machine.

As far as office goes, you can easily choose using the config options in the script to not enable office hardening.
As with any hardening, some things break. Pretty much all extensions are a no go in office. They are generally a security nightmare. That being said, we've included multiple warnings. You're supposed to test any hardening script on a non production machine before running it on one you actually use.

**Comment by LinuxOnTheDesktop** [comment]
>  you can easily choose using the config options in the script to not enable office hardening.

It is worth pointing out, to any third party that might read this exchange, that the script will not solicit the setting of options. Rather, one must _edit_ the script.

**Comment by simeononsecurity** [comment]
> > you can easily choose using the config options in the script to not enable office hardening.
> 
> It is worth pointing out, to any third party that might read this exchange, that the script will not solicit the setting of options. Rather, one must _edit_ the script.

Please read the readme before running scripts on the internet, there are toggle-able options. It's up to you to do the reading. You should never run random scripts on the internet without reading the readme and testing in a vm or otherwise non-production system, ours included.
https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat#manual-install
