### ISSUE TITLE
Browser Settings cannot be changed

### ISSUE THREAD

**Issue by mmalikz** [simeononsecurity/Windows-Optimize-Harden-Debloat#13]
Great work on the script, however, i am having issues with my browsers not saving any history / cache / cookies and everything is removed upon any restart to the machine. 

I tried via regedit to change the policies like unblocking about:config in:
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Mozilla\Firefox
or disabling this:
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Mozilla\Firefox\SanitizeOnShutdown

however, it seems like any changes done to the registry is reverted back to the secure settings set by the script after restarting the machine. This is done automatically, and no matter what policies i change from the registry it all reverts back to block about:config and enable sanitize.on.shutdown policies. 

Is there a way to stop the script from changing the browser policies <stig> and allow browsers to save cookies / history / cache and make sure that the policies stay the same even after a restart. 

Thank you in advance

**Comment by simeononsecurity** [comment]
So, the answer to this may be a bit technical...

Download this repo [here](https://github.com/simeononsecurity/STIG-Compliant-Domain-Prep/archive/refs/heads/master.zip)
The files you want are in ```.\Files\PolicyDefinitions\``` inside that repo. You'll want to download the entire repo and extract the zip file.
Copy the contents of that folder to C:\Windows\PolicyDefinitions\
Those are the template files you need to see the group policies that are applied.

On your system, type ```gpedit.msc``` and navigate to ``` Computer Settings > Administrative Templates > Mozilla```. Then sort by state/status so that Enabled is at the top and Disabled is at the bottom. You'll find your settings there. Modify/Disable what you need there and reboot your system.

**Comment by simeononsecurity** [comment]
In the future, we are looking into setting up the script to allow users to choose what portions of the script they want.
For now this is the best we can do. Thanks for submitting this issue.

**Comment by mmalikz** [comment]
fantastic, it worked!  thank you simeon
