### ISSUE TITLE
Start Menu isn't working.

### ISSUE THREAD

**Issue by payday2123** [simeononsecurity/Windows-Optimize-Harden-Debloat#17]
After using this script, I get an eror message, that my Start Menu isn't working, and even after restarting it won't work anymore

**Comment by simeononsecurity** [comment]
@payday2123 

Please provide the following information:
- Operating System version. Ex 1909, 20H2, 21H1, etc.
- Confirm your computer meets the requirements listed in the [readme](https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat/blob/master/README.md)
- Screenshot/record the issue and post or a link to it here.

**Comment by simeononsecurity** [comment]
By any chance are you using a 3rd party start menu like StartMenu8, Classic Shell, or Start10?

We've tested the script quite a bit on different configurations. As far as messing with the start menu the script doesn't actually make many changes. It used to reset all pins on the start menu but no longer does that. 

Currently all the script does with regards to the start menu is:
- Block automatic app installations
- Disables Bing in Windows Search
- Disables Cloud Syncing of your Start Menu Layout
- Disables Start Menu Suggestions
- Disables Tracking of App Starts
- Remove OneDrive Start Menu Entry

Nothing there really affects the start menu. I'm not lead to believe that it's the script that is the issue here.

Have you run any other scripts or made any changes yourself recently?

**Comment by simeononsecurity** [comment]
Since this issue was not able to be recreated in a lab and the submitter @payday2123  failed to submit additional details as requested, we are closing this issue.
