### ISSUE TITLE
Microsoft store

### ISSUE THREAD

**Issue by nsk** [simeononsecurity/Windows-Optimize-Harden-Debloat#19]
Microsoft store is no longer accessible on windows 11 after installing the script
[https://i.imgur.com/0IDYRiU.jpeg](url)

possibility of rollback or uninstallation of the script ?

**Comment by simeononsecurity** [comment]
Please see the following for more information on this issue.

https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat/issues/16
https://github.com/simeononsecurity/Windows-Optimize-Debloat/issues/1

**Comment by simeononsecurity** [comment]
Rollback is not currently supported by this script. As per the readme, you are to test this before running on any production system.

The microsoft store is not supported by this script as it requires a microsoft account, which is disabled for multiple documented reasons. Additionally, the license manager service is disabled with the script. This is because no security and privacy aware user should be using the microsoft store to begin with. Microsoft's appx and the Microsoft Store are not supported by this script or by us in any way. 

For you, our suggestion is to read the documentation before running any script, including ours, and to either restore to a snapshot or reinstall windows.
