### ISSUE TITLE
Can't get past the lock screen after reboot

### ISSUE THREAD

**Issue by d1lanX** [simeononsecurity/Windows-Optimize-Harden-Debloat#33]
After rebooting there's no way to get past the login screen. 

"Other User"
Please type in user and password to continue... 

Considering I didn't have any password configured on my computer I don't know why does it ask for one.

**Comment by simeononsecurity** [comment]
Hi there if you read the readme of the script
It links to documentation for the standards for a highly secure device. In addition, linked below the previously mentioned are the dod configuration guidelines. 

Accounts with no password as well as accounts linked to a Microsoft account aren't allowed. 

If you know your username from before it might be worth trying leaving the password field blank and trying to sign in. 
Otherwise, you'll have to reinstall windows to resolve your issues.

For less experienced users, please use the following script as it has no hardening and much less gotchas.  https://github.com/simeononsecurity/Windows-Optimize-Debloat

Lastly, please read the readme before running any code off GitHub. Especially so if you're unable to review the code yourself. This goes for all repos, not just ours. 

Unfortunately, if you can't get back into your account there is nothing we can really help you with.
