### ISSUE TITLE
After Installing it broke essential applications to my system including .NET

### ISSUE THREAD

**Issue by BrodyGirton** [simeononsecurity/Windows-Optimize-Harden-Debloat#74]
**Describe the bug**
After installing the non GUI version, I notcied that chocolatey did not work aswell as various other applications that use .NET. Plus my computer says its now managed by an organization so the system is limited. Its definately somewhat my fault but how can I reset this

**To Reproduce**
I do not know myself how to reproduce it

**Expected behavior**
A simple non system breaking debloat
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser; Ungoogled Chromium
 - Version 22H2

**Comment by simeononsecurity** [comment]
> **Describe the bug** A clear and concise description of what the bug is. After installing the non GUI version, I notcied that chocolatey did not work aswell as various other applications that use .NET. Plus my computer says its now managed by an organization so the system is limited. Its definately somewhat my fault but how can I reset this
> 
> **To Reproduce** I do not know myself how to reproduce it
> 
> **Expected behavior** A clear and concise description of what you expected to happen. A simple non system breaking debloat **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
>     * OS: Windows 10
> 
>     * Browser; Ungoogled Chromium
> 
>     * Version 22H2

The script applies some settings via GPO. That will make that banner pop up. There is no way to disable that banner.
If you're curious to learn how to modify the configurations please read
https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat#editing-policies-in-local-group-policy-after-the-fact

It is possible to break chocolatey under some specific configurations.
Please read https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat#ssl-issues-with-chocolatey

If you're like to revert, please google "how to perform a windows system restore". The script takes a restore point before making any changes.

However, if you'd like to work on fixing your configuration, we'll need to know what version of the non-gui installer you used. 
There are three

The automated, the chocolatey, and the manual install
If you used the manual install, we'll need to know with what flags you used.
Additionally, FYI, it isn't enough to say "this broke x". Please come into this with descriptions of what broke and in what way. Screenshots, logs, etc are a bonus. If you're unable to do this, you shouldn't be running scripts from anyone.

In the readme it states "Do not run this script if you don't understand what it does. It is your responsibility to review and test the script before running it." https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat#notes-warnings-and-considerations

Which we know you didn't read because many of the things you've discussed are already documented there.

We have to tell many people this, but slow down a bit. Take the time to read and follow instructions. If you're really smart, you'll take the time to test and understand them. Privacy and security are a marathon, not a sprint.

**Comment by simeononsecurity** [comment]
Closed for inactivity
